### ISSUE TITLE
Forms - Input Fields: Update all input fields' height to 48px (currently 54px)

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#339] opened 2016-08-29 19:12 UTC
![screen shot 2016-08-29 at 3 11 27 pm](https://cloud.githubusercontent.com/assets/19931482/18063909/01e9cb98-6dfb-11e6-81f7-bc206e27d0d3.png)

**Comment by pmmck** [comment] 2016-09-01 18:51
Input heights should match button heights.

**Comment by RachelRVasquez** [comment] 2016-09-02 16:11
@pmmck This looks like a similar discrepancy that we had for the buttons between the browser and Zeplin's specs. Currently the top/bottom padding for fields match Zeplin and do not naturally match Zeplin's height in the browser. Are we okay to go against Zeplin specs and reduce padding to keep the fields at a natural height of 48px in browser?

cc: @fuhton

**Comment by pmmck** [comment] 2016-09-02 19:02
@RachelRVasquez the fields in Zeplin are 48px tall, as far as I can see.   Sounds like you need to update the line-height or padding in the CSS to get them to match.  Thanks so much.

cc @fuhton

**Comment by pmmck** [comment] 2016-09-07 16:20
@RachelRVasquez @fuhton following up here.   

![zeplin input height](https://cloud.githubusercontent.com/assets/385391/18319744/10a22a12-74f5-11e6-8454-935e99088da6.png)

Here's a screenshot from Zeplin showing that the spec calls for a 16px input value, with a 16px line-height (single line inputs don't wrap) and 16px top and bottom padding.    That's 48px tall.

It looks like the current font size for the placeholder / value is 14px/20px which might be part of the issue.

To be sure an inline form with a submit button all align at 48px, either the padding needs to be reduced by 2px to account for the border, or an inner-shadow needs to be used instead of a border.

Thanks!

**Comment by fuhton** [comment] 2016-09-07 16:54
@RachelRVasquez Thoughts on this?

**Comment by RachelRVasquez** [comment] 2016-09-07 18:38
@pmmck @fuhton 

I've corrected the font-size issue that was happening on one of the sites due to legacy styles. With the font-size change however, we will still have to reduce the padding on the inputs from their 16px 12px so the fields will naturally be 48px in the browser. Will create a duplicate of this ticket in Trello so we can move forward with that there. Thanks!

**Closed by RachelRVasquez** 2016-09-07 18:38 UTC
