### ISSUE TITLE
Forms - Checkboxes with error: Update spacing between first and second error message, and between second error message and first option to 16px

### ISSUE THREAD

**Issue by jdrf-digitaldesigner** [JDRF/design-system#343] opened 2016-08-29 19:24 UTC
![screen shot 2016-08-29 at 3 24 01 pm](https://cloud.githubusercontent.com/assets/19931482/18064278/a6f66884-6dfc-11e6-9e13-7e984e439195.png)

**Comment by RachelRVasquez** [comment] 2016-09-02 16:34
I've created a duplicate of this issue in Trello instead. Will continue progress/conversation there.

**Closed** 2016-09-02 16:40 UTC
