### ISSUE TITLE
IE9/10, Windows 7: Checkbox buttons aren't working properly

### ISSUE THREAD

**Issue by briansaycocie** [JDRF/design-system#60] opened 2016-06-03 16:40 UTC
Might be related to #51.

When clicked, the buttons do not toggle to the correct state.

![woytjlqqpo](https://cloud.githubusercontent.com/assets/1328262/15786011/eaee2110-297f-11e6-84ad-6668ed590e58.gif)

**Comment by fuhton** [comment] 2016-06-03 16:45
Duplicate of #51

**Closed by fuhton** 2016-06-03 16:45 UTC
Labels: bug, duplicate
